apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-gitops-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:amdadulbari/cloudnative-gitops.git
  sshPrivateKey: |